data = [
    {
        'account_name': 'cristiano',
        'real_name': 'Cristiano Ronaldo',
        'follower_count': 619,
        'description': 'Footballer',
        'country': 'Portugal',
    },
    {
        'account_name': 'selenagomez',
        'real_name': 'Selena Gomez',
        'follower_count': 429,
        'description': 'Singer/Actress',
        'country': 'United States',
    },
    {
        'account_name': 'leomessi',
        'real_name': 'Lionel Messi',
        'follower_count': 489,
        'description': 'Footballer',
        'country': 'Argentina',
    },
    {
        'account_name': 'beyonce',
        'real_name': 'Beyoncé',
        'follower_count': 319,
        'description': 'Singer',
        'country': 'United States',
    },
    {
        'account_name': 'fcbarcelona',
        'real_name': 'FC Barcelona',
        'follower_count': 125,
        'description': 'Football Club',
        'country': 'Spain',
    },
    {
        'account_name': 'nasa',
        'real_name': 'NASA',
        'follower_count': 97.2,
        'description': 'Space agency',
        'country': 'United States',
    },
    {
        'account_name': 'virat.kohli',
        'real_name': 'Virat Kohli',
        'follower_count': 266,
        'description': 'Cricketer',
        'country': 'India',
    },
    {
        'account_name': 'bbcnews',
        'real_name': 'BBC News',
        'follower_count': 27,
        'description': 'News organization',
        'country': 'United Kingdom',
    },
    {
        'account_name': 'ladygaga',
        'real_name': 'Lady Gaga',
        'follower_count': 57,
        'description': 'Singer/Actress',
        'country': 'United States',
    },
    {
        'account_name': 'weareone.exo',
        'real_name': 'EXO',
        'follower_count': 10,
        'description': 'K-pop group',
        'country': 'South Korea',
    },
    {
        'account_name': 'serenawilliams',
        'real_name': 'Serena Williams',
        'follower_count': 17,
        'description': 'Tennis player',
        'country': 'United States',
    },
    {
        'account_name': 'natgeotravel',
        'real_name': 'National Geographic Travel',
        'follower_count': 30,
        'description': 'Travel exploration',
        'country': 'United States',
    },
    {
        'account_name': 'instagram',
        'real_name': 'Instagram',
        'follower_count': 668,
        'description': 'Social media platform',
        'country': 'United States',
    },
    {
        'account_name': 'twitch',
        'real_name': 'Twitch',
        'follower_count': 6.5,
        'description': 'Streaming platform',
        'country': 'United States',
    },
    {
        'account_name': 'shakira',
        'real_name': 'Shakira',
        'follower_count': 90.5,
        'description': 'Singer',
        'country': 'Colombia',
    },
    {
        'account_name': 'oprah',
        'real_name': 'Oprah Winfrey',
        'follower_count': 22,
        'description': 'Media mogul',
        'country': 'United States',
    },
    {
        'account_name': 'iamcardib',
        'real_name': 'Cardi B',
        'follower_count': 169,
        'description': 'Rapper',
        'country': 'United States',
    },
    {
        'account_name': 'akshaykumar',
        'real_name': 'Akshay Kumar',
        'follower_count': 67.6,
        'description': 'Actor',
        'country': 'India',
    },
    {
        'account_name': 'realmadrid',
        'real_name': 'Real Madrid',
        'follower_count': 152,
        'description': 'Football Club',
        'country': 'Spain',
    },
    {
        'account_name': 'marvel',
        'real_name': 'Marvel',
        'follower_count': 67.1,
        'description': 'Entertainment company',
        'country': 'United States',
    },
    {
        'account_name': 'hrithikroshan',
        'real_name': 'Hrithik Roshan',
        'follower_count': 47.3,
        'description': 'Actor',
        'country': 'India',
    },
    {
        'account_name': 'camerondallas',
        'real_name': 'Cameron Dallas',
        'follower_count': 26.9,
        'description': 'Influencer',
        'country': 'United States',
    },
    {
        'account_name': 'youtube',
        'real_name': 'YouTube',
        'follower_count': 31,
        'description': 'Video platform',
        'country': 'United States',
    },
    {
        'account_name': 'floydmayweather',
        'real_name': 'Floyd Mayweather',
        'follower_count': 29.6,
        'description': 'Boxer',
        'country': 'United States',
    },
    {
        'account_name': 'nytimes',
        'real_name': 'The New York Times',
        'follower_count': 17,
        'description': 'News organization',
        'country': 'United States',
    },
    {
        'account_name': 'voguemagazine',
        'real_name': 'Vogue Magazine',
        'follower_count': 47.7,
        'description': 'Fashion magazine',
        'country': 'United States',
    },
    {
        'account_name': 'pewdiepie',
        'real_name': 'PewDiePie',
        'follower_count': 21.3,
        'description': 'YouTuber',
        'country': 'Sweden',
    },
    {
        'account_name': 'thesimpsons',
        'real_name': 'The Simpsons',
        'follower_count': 1.8,
        'description': 'Animated TV show',
        'country': 'United States',
    },
    {
        'account_name': 'jlo',
        'real_name': 'Jennifer Lopez',
        'follower_count': 253,
        'description': 'Singer/Actress',
        'country': 'United States',
    },
    {
        'account_name': 'nike',
        'real_name': 'Nike',
        'follower_count': 80,
        'description': 'Sportswear company',
        'country': 'United States',
    },
    {
        'account_name': 'bbcbreakfast',
        'real_name': 'BBC Breakfast',
        'follower_count': 15,
        'description': 'News program',
        'country': 'United Kingdom',
    },
    {
        'account_name': 'imacelebrity',
        'real_name': 'Im a Celebrity...',
        'follower_count': 1.6,
        'description': 'Reality TV show',
        'country': 'United Kingdom',
    },
    {
        'account_name': 'justinbieber',
        'real_name': 'Justin Bieber',
        'follower_count': 292,
        'description': 'Singer',
        'country': 'Canada',
    },
    {
        'account_name': 'nfl',
        'real_name': 'NFL',
        'follower_count': 29,
        'description': 'American Football League',
        'country': 'United States',
    },
    {
        'account_name': 'warnerbrosentertainment',
        'real_name': 'Warner Bros. Entertainment',
        'follower_count': 6.3,
        'description': 'Entertainment company',
        'country': 'United States',
    },
    {
        'account_name': 'realmadridwomen',
        'real_name': 'Real Madrid Women',
        'follower_count': 5,
        'description': 'Football Club',
        'country': 'Spain',
    },
    {
        'account_name': 'spotify',
        'real_name': 'Spotify',
        'follower_count': 11,
        'description': 'Music streaming platform',
        'country': 'Sweden',
    },
    {
        'account_name': 'iamsrk',
        'real_name': 'Shah Rukh Khan',
        'follower_count':46,
        'description': 'Actor',
        'country': 'India',
    },
    {
        'account_name': 'liltunechi',
        'real_name': 'Lil Wayne',
        'follower_count': 18,
        'description': 'Rapper',
        'country': 'United States',
    },
    {
        'account_name': 'paulpogba',
        'real_name': 'Paul Pogba',
        'follower_count': 47,
        'description': 'Footballer',
        'country': 'France',
    },
    {
        'account_name': 'jimmyfallon',
        'real_name': 'Jimmy Fallon',
        'follower_count': 26,
        'description': 'TV Host/Comedian',
        'country': 'United States',
    },
    {
        'account_name': 'fcbayern',
        'real_name': 'FC Bayern Munich',
        'follower_count': 41,
        'description': 'Football Club',
        'country': 'Germany',
    },
    {
        'account_name': 'espn',
        'real_name': 'ESPN',
        'follower_count': 26,
        'description': 'Sports network',
        'country': 'United States',
    },
    {
        'account_name': 'davidbeckham',
        'real_name': 'David Beckham',
        'follower_count': 86.8,
        'description': 'Footballer',
        'country': 'United Kingdom',
    },
    {
        'account_name': 'fcbarcelonawomen',
        'real_name': 'FC Barcelona Women',
        'follower_count': 8,
        'description': 'Football Club',
        'country': 'Spain',
    },
    {
        'account_name': 'shawnmendes',
        'real_name': 'Shawn Mendes',
        'follower_count': 81,
        'description': 'Singer',
        'country': 'Canada',
    },
    {
        'account_name': 'easportsfifa',
        'real_name': 'EA Sports FIFA',
        'follower_count': 32,
        'description': 'Video game company',
        'country': 'United States',
    },
    {
        'account_name': 'jamescharles',
        'real_name': 'James Charles',
        'follower_count': 35,
        'description': 'YouTuber/Makeup artist',
        'country': 'United States',
    },
    {
        'account_name': 'kingjames',
        'real_name': 'LeBron James',
        'follower_count': 159,
        'description': 'Basketball player',
        'country': 'United States',
    },
]
